name:               "Code IPP"
description:        "J'ai pas d'idée de description"

url:                ""
author:             "Les croix IPP"
email:              "Lel@yopmail.com"
image_swagg:        "https://scontent-arn2-1.xx.fbcdn.net/v/t1.0-9/17800369_1026235704179829_2170041278528142055_n.jpg?oh=ba3b19146d14736dc9e60b1706c7cc7c&oe=5954CA9F"
twitter:            "KimKardashian"
github:             "nix29178/codeIPP"
facebook:           "IhavenomemesImustshitpost/videos/634145143453730/"

disqus_shortname:   "thinker3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
